### ISSUE TITLE
BRP gegevens opladen in IRMA - Session timeout, please try again

### ISSUE THREAD

**Issue by rgerbranda** [GemeenteNijmegen/irma-brp-opladen#4]
Als ik mijn gegevens opvraag, krijg ik kort een IRMA QR-code in beeld en direct daarna de melding "Session timeout, please try again"

**Comment by BramWithaar** [comment]
excuses voor de wat late reactie. Op welke omgeving is dit, https://services-test.nijmegen.nl of https://services.nijmegen.nl? Op services-test hebben we een tijdje een storing gehad, maar die is inmiddels weer verholpen.

**Comment by rgerbranda** [comment]
Ik krijg dit op services.nijmegen.nl

Bijgevoegd heb ik de stack trace van IRMA

![img_2694](https://user-images.githubusercontent.com/11868439/46942829-786a1c00-d06e-11e8-8c9e-d1f9d4ecc99b.PNG)
![img_2695](https://user-images.githubusercontent.com/11868439/46942830-786a1c00-d06e-11e8-9f20-ec30a14bb177.PNG)
![img_2696](https://user-images.githubusercontent.com/11868439/46942831-786a1c00-d06e-11e8-9739-32689486b996.PNG)
![img_2697](https://user-images.githubusercontent.com/11868439/46942832-786a1c00-d06e-11e8-9e02-f80c7a4da814.PNG)
![img_2698](https://user-images.githubusercontent.com/11868439/46942833-786a1c00-d06e-11e8-9fc7-7a64c7b84b86.PNG)

**Comment by marnixdessing** [comment]
@BramWithaar kan deze gesloten worden (na 4 jaar)?

**Comment by BramWithaar** [comment]
hmm, ja, dit is destijds een hickupje geweest.
