### ISSUE TITLE
Test maken voor BRP api-endpoint

### ISSUE THREAD

**Issue by BramWithaar** [GemeenteNijmegen/irma-brp-opladen#6]
We hebben geen tests waardoor we bij wijzigingen (fixes) in de api lastig kunnen achterhalen of er dingen stuk gaan.
Voor een hele set aan BSN's tests maken waarbij de output van de bestaande situatie kan worden vergeleken met output van een aanpassing zodat er meer zekerheid is dat er geen onverwachte wijzigingen in data zijn.

**Comment by marnixdessing** [comment]
Uitzoeken wat handige aanpak is hiervoor:
- Testen op live accp api (ontoerijkende test data?)
- XSLT berchten voor en na

**Comment by joostvanderborg** [comment]
Er zitten in Mijn Nijmegen een paar simpele tests die ook de BRP-api gebruiken, mogelijk heb je daar wat aan?

**Comment by marnixdessing** [comment]
ZIe repo https://github.com/GemeenteNijmegen/brp-irma-api-tests
