### ISSUE TITLE
Policy Falsified error na re-issue

### ISSUE THREAD

**Issue by MartijnvDijk** [GemeenteNijmegen/irma-brp-opladen#7]
Bij het 'inloggen' met IRMA op de test site (https://services-test.nijmegen.nl/irma/gemeente/start) komt de volgende foutmelding bij het 're-issue-final':

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
<soapenv:Body>
<soapenv:Fault>
<faultcode>soapenv:Server</faultcode>
<faultstring>Policy Falsified</faultstring>
<faultactor>
https://services-test.nijmegen.nl/irma/gemeente/re-issue-final
</faultactor>
<detail>
<l7:policyResult xmlns:l7="http://www.layer7tech.com/ws/policy/fault" status="Error in Assertion Processing"/>
</detail>
</soapenv:Fault>
</soapenv:Body>
</soapenv:Envelope>
```

**Comment by BramWithaar** [comment]
dit moet op L7 even uitgezocht worden via de logging daar om te zien wat er precies misgaat. Moet @WHueting dus wat tijd aan besteden.

**Comment by MartijnvDijk** [comment]
3 problemen gevonden op Layer7. Inloggen met Digid, inloggen met IRMA en issue-manual. De laatste gaan we laten oplossen door ESB (ticket ICT Servicedesk) De rest laten we voor nu omdat binnenkort de nieuwe IRMA issue site live gaat.
